### ISSUE TITLE
Error - libraries dependency

### ISSUE THREAD

**Issue by AMergy** [AMergy/genre_classification#1]
Conflicts between libraries leading to this error:
```

Traceback (most recent call last):

File "/home/anne/projects/udacity/genre_classification/download/download_data.py", line 5, in <module>

import wandb

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/__init__.py", line 38, in <module>

from wandb import sdk as wandb_sdk

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/sdk/__init__.py", line 12, in <module>

from .wandb_init import init # noqa: F401

^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 29, in <module>

from .backend.backend import Backend

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/sdk/backend/backend.py", line 18, in <module>

from ..internal.internal import wandb_internal

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/sdk/internal/internal.py", line 34, in <module>

from . import sender

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 18, in <module>

from wandb.filesync.dir_watcher import DirWatcher

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/filesync/dir_watcher.py", line 10, in <module>

wd_polling = util.vendor_import("watchdog.observers.polling")

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/util.py", line 170, in vendor_import

module = import_module(name)

^^^^^^^^^^^^^^^^^^^

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/importlib/__init__.py", line 126, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/vendor/watchdog/observers/__init__.py", line 63, in <module>

from .inotify import InotifyObserver as Observer

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/vendor/watchdog/observers/inotify.py", line 76, in <module>

from watchdog.observers.api import (

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/vendor/watchdog/observers/api.py", line 23, in <module>

from watchdog.utils.bricks import SkipRepeatsQueue

File "/home/anne/miniconda3/envs/mlflow-a5715092c76d3d961b0ce679f331bae757720012/lib/python3.11/site-packages/wandb/vendor/watchdog/utils/bricks.py", line 175, in <module>

class OrderedSet(collections.MutableSet):

^^^^^^^^^^^^^^^^^^^^^^

AttributeError: module 'collections' has no attribute 'MutableSet'

Traceback (most recent call last):

File "/home/anne/projects/udacity/genre_classification/main.py", line 28, in go

_ = mlflow.run(

File "/home/anne/miniconda3/envs/mlflow-8346854d0da20edf533f8fc775c56254640eaa69/lib/python3.9/site-packages/mlflow/projects/__init__.py", line 355, in run

_wait_for(submitted_run_obj)

File "/home/anne/miniconda3/envs/mlflow-8346854d0da20edf533f8fc775c56254640eaa69/lib/python3.9/site-packages/mlflow/projects/__init__.py", line 372, in _wait_for

raise ExecutionException("Run (ID '%s') failed" % run_id)

mlflow.exceptions.ExecutionException: Run (ID '21ec1ea77adb433fa3d001978a5ef422') failed

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

2023/04/03 10:56:04 ERROR mlflow.cli: === Run (ID 'f041397e812b46529bc673a9a626a0cd') failed ===

```

**Comment by AMergy** [comment]
Debug with `mlflow run . -P hydra_options="main.execute_steps='download,preprocess,check_data'"`
